app_default:
  resource: "@AppBundle/Resources/config/routing/default.yml"
  prefix: /

app_aziende:
  resource: "@AppBundle/Resources/config/routing/aziende.yml"
  prefix: /aziende

app_news:
  resource: "@AppBundle/Resources/config/routing/news.yml"
  prefix: /news