BackendBundle\Entity\Bannerfix:
    type: entity
    table: BannerFix
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 2048
            options:
                fixed: false
    lifecycleCallbacks: {  }
