BackendBundle\Entity\Bannertop:
    type: entity
    table: BannerTop
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
