BackendBundle\Entity\NewsVisitas:
    type: entity
    table: news_visitas
    indexes:
        newsID:
            columns:
                - newsID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        newsid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: newsID
        typeNews:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: type_news
        visitas:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
