BackendBundle\Entity\News:
    type: entity
    table: News
    indexes:
        type:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        titolo:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        fonte:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        descrizione:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        galleria:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        youtubeCode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: youtube_code
        priority:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
