BackendBundle\Entity\Utenti:
    type: entity
    table: Utenti
    uniqueConstraints:
        unique:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        isAdmin:
            type: boolean
            nullable: false
            column: is_admin
        isNews:
            type: boolean
            nullable: false
            column: is_news
        confirmed:
            type: boolean
            nullable: false
        hash:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        tsCk:
            type: string
            nullable: false
            length: 14
            options:
                fixed: false
            column: ts_ck
    lifecycleCallbacks: {  }
